# .latexmkrc generated by CMake from UseLatexMk.cmake starts here

$out_dir = "@CMAKE_CURRENT_BINARY_DIR@"
$pdf_mode = 1;
$pdflatex = "@PDFLATEX_COMPILER@ -shell-escape -interaction=nonstopmode %O %S";

# .latexmkrc generated by CMake from UseLatexMk.cmake ends here
